# gks_family_compare_table.jl  —  Part 3 of 3.
# Joins lamgplus.csv (Part 1) and orig.csv (Part 2) into the LaTeX table for App.~\ref{sec:families}.
# Run: julia scripts/gks_family_compare_table.jl   (writes doc/gks_compare_table.tex)
using DelimitedFiles, Printf

scratch = get(ENV, "SCRATCH", joinpath(@__DIR__, "..", "results", "gks_cmp"))
function readcsv(f)
    d = readdlm(joinpath(scratch, f), ','; header=true)
    rows = d[1]; cols = vec(d[2]); Dict(cols[j] => rows[:,j] for j in 1:length(cols))
end
lp = readcsv("lamgplus.csv"); og = readcsv("orig.csv")

commas(x) = replace(@sprintf("%d", x), r"(?<=\d)(?=(\d{3})+$)" => ",")
sci(x) = (s = @sprintf("%.1e", x); m = match(r"([0-9.]+)e([+-]?)0*(\d+)", s);
          string(m.captures[1], raw"\!\times\!10^{", m.captures[2]=="-" ? "-" : "", m.captures[3], "}"))

orig_idx = Dict(og["name"][i] => i for i in 1:length(og["name"]))
io = IOBuffer()
println(io, raw"\begin{table}[t]\centering")
println(io, raw"\caption{The original MATLAB LAMG 2.2.1 vs.\ LAMG+ on the families of Spielman's")
println(io, raw"approximate-Cholesky benchmark \cite{gks2023}, \emph{same graph and right-hand side}. Each")
println(io, raw"family is generated by Spielman's own \texttt{Laplacians.jl}; LAMG 2.2.1 is run under GNU")
println(io, raw"Octave (compatibility shims only---multigrid algorithm and MEX kernels unchanged) with")
println(io, raw"gks2023's exact solver call (\texttt{setup(`laplacian',$\cdot$)}, \texttt{errorReductionTol}$=10^{-8}$,")
println(io, raw"default cycle cap). Although \cite{gks2023} report LAMG as non-convergent across all of these")
println(io, raw"families, the unmodified 2.2.1 in fact converges on \emph{every} one; LAMG+ reaches a strict")
println(io, raw"$10^{-8}$ residual in as few or fewer cycles. ``cyc''~=~multigrid cycles; relres~=~$\|L\phi-b\|/\|b\|$ at")
println(io, raw"termination. (LAMG 2.2.1's \texttt{errorReductionTol} test targets the error norm, so its residual")
println(io, raw"lands within a small factor of $10^{-8}$---e.g.\ $3.2\!\times\!10^{-8}$ for uniform-weight chimera.)}")
println(io, raw"\label{tab:lamgorig}")
println(io, raw"\begin{tabular}{l r r r r r r}")
println(io, raw"\toprule")
println(io, raw" & & & \multicolumn{2}{c}{LAMG 2.2.1} & \multicolumn{2}{c}{LAMG+}" * "\\\\")
println(io, raw"\cmidrule(lr){4-5}\cmidrule(lr){6-7}")
println(io, raw"Family & $n$ & $m$ & cyc & relres & cyc & relres" * "\\\\")
println(io, raw"\midrule")
for i in 1:length(lp["name"])
    nm = lp["name"][i]; j = orig_idx[nm]
    fam = lp["family"][i]
    @printf(io, "%s & %s & %s & %d & \$%s\$ & %d & \$%s\$\\\\\n",
        fam, commas(Int(lp["n"][i])), commas(Int(lp["m"][i])),
        Int(og["orig_cycles"][j]), sci(og["orig_relres"][j]),
        Int(lp["lamgplus_cycles"][i]), sci(lp["lamgplus_relres"][i]))
end
println(io, raw"\bottomrule")
println(io, raw"\end{tabular}")
println(io, raw"\end{table}")

tex = String(take!(io))
outpath = joinpath(@__DIR__, "..", "doc", "gks_compare_table.tex")
write(outpath, tex)
println(tex); println("\nWrote ", outpath)
