# gks_family_compare.jl  —  Part 1 of 3 (Julia / LAMG+ side).
#
# Reproduces the "original LAMG vs LAMG+ on Spielman's families" table (\S\ref{sec:families},
# Table~\ref{tab:lamgorig}). For each gks2023 test family (generated by Spielman's own
# Laplacians.jl, plus the SPE10 reservoir Laplacian and a grounded-SDDM chimera) this:
#   (1) builds the operator A and a compatible RHS b,
#   (2) solves with LAMG+ (this repo) and records cycles + relative residual,
#   (3) exports the IDENTICAL (A, b) to text so Part 2 runs the ORIGINAL MATLAB LAMG 2.2.1 on
#       the same system via gks2023's own invocation.
# Two operator kinds: 'laplacian' (singular graph Laplacian; b = L*x_true, zero-mean) and 'sdd'
# (nonsingular SDDM, here a grounded chimera; b = M*x_true). LAMG+ has no native SDDM path, so the
# SDDM system is solved by the standard grounded-Laplacian lift; the original LAMG uses its native
# setup('sdd',.) in Part 2 (gks2023's matlab/timeLamgSddm.m). Both solve the SAME M.
#
# Run:  julia --project=examples/repro_env scripts/gks_family_compare.jl
# Outputs under $SCRATCH (default results/gks_cmp/):
#   <name>_A.txt, <name>_b.txt   — operator (IJV) and RHS, one per family
#   manifest.csv                  — family,name,n,m,mode   (read by Part 2)
#   lamgplus.csv                  — family,name,n,m,mode,lamgplus_cycles,lamgplus_relres,lamgplus_ok
using LAMG, Laplacians, SparseArrays, LinearAlgebra, Random, Statistics, Printf, DelimitedFiles

scratch = get(ENV, "SCRATCH", joinpath(@__DIR__, "..", "results", "gks_cmp"))
mkpath(scratch)
tol = 1e-8

# ---- grid stressors (uniform grids come from Laplacians.grid2/grid3) ----
function grid_aniso2(P; wx=1.0, wy=1e-4)
    idx(i,j)=(j-1)*P+i; I=Int[];J=Int[];V=Float64[]
    for j in 1:P, i in 1:P
        i<P && (push!(I,idx(i,j));push!(J,idx(i+1,j));push!(V,wx))
        j<P && (push!(I,idx(i,j));push!(J,idx(i,j+1));push!(V,wy))
    end
    W=sparse(I,J,V,P*P,P*P); W+W'
end
function grid_hicon2(P; rng)
    idx(i,j)=(j-1)*P+i; I=Int[];J=Int[];V=Float64[]
    for j in 1:P, i in 1:P
        i<P && (push!(I,idx(i,j));push!(J,idx(i+1,j));push!(V,10.0^(6rand(rng)-3)))
        j<P && (push!(I,idx(i,j));push!(J,idx(i,j+1));push!(V,10.0^(6rand(rng)-3)))
    end
    W=sparse(I,J,V,P*P,P*P); W+W'
end
function grid_aniso3(P; wx=1.0, wy=1e-4, wz=1e-4)
    lin(i,j,k)=i+P*(j-1)+P*P*(k-1); I=Int[];J=Int[];V=Float64[]
    for k in 1:P, j in 1:P, i in 1:P
        i<P && (push!(I,lin(i,j,k));push!(J,lin(i+1,j,k));push!(V,wx))
        j<P && (push!(I,lin(i,j,k));push!(J,lin(i,j+1,k));push!(V,wy))
        k<P && (push!(I,lin(i,j,k));push!(J,lin(i,j,k+1));push!(V,wz))
    end
    W=sparse(I,J,V,P^3,P^3); W+W'
end
function grid_hicon3(P; rng)
    lin(i,j,k)=i+P*(j-1)+P*P*(k-1); I=Int[];J=Int[];V=Float64[]
    for k in 1:P, j in 1:P, i in 1:P
        i<P && (push!(I,lin(i,j,k));push!(J,lin(i+1,j,k));push!(V,10.0^(6rand(rng)-3)))
        j<P && (push!(I,lin(i,j,k));push!(J,lin(i,j+1,k));push!(V,10.0^(6rand(rng)-3)))
        k<P && (push!(I,lin(i,j,k));push!(J,lin(i,j,k+1));push!(V,10.0^(6rand(rng)-3)))
    end
    W=sparse(I,J,V,P^3,P^3); W+W'
end
function read_mtx_sym(path)              # symmetric coordinate .mtx -> adjacency W
    I=Int[];J=Int[];V=Float64[];n=0
    open(path) do io
        readline(io); l=readline(io); while startswith(strip(l),"%"); l=readline(io); end
        n=parse(Int,split(l)[1])
        for ln in eachline(io)
            p=split(ln); isempty(p) && continue
            i=parse(Int,p[1]); j=parse(Int,p[2]); v=length(p)>=3 ? parse(Float64,p[3]) : 1.0
            push!(I,i);push!(J,j);push!(V,v); i!=j && (push!(I,j);push!(J,i);push!(V,v))
        end
    end
    sparse(I,J,V,n,n)
end

rng = MersenneTwister(2024)
spe10 = joinpath(@__DIR__, "..", "data", "SPE__spe10_2_nz20.mtx")
# (label, file name, mode, builder -> adjacency W) ; :spe10 marks the external loader
families = Any[
    ("chimera (unweighted)",    "chimera",       :lap, () -> chimera(50_000, 35)),
    ("chimera (uniform wt)",    "uni_chimera",   :lap, () -> uni_chimera(50_000, 25)),
    ("chimera (weighted)",      "wted_chimera",  :lap, () -> wted_chimera(50_000, 1)),
    ("chimera (SDDM)",          "sddm_chimera",  :sdd, () -> chimera(50_000, 35)),
    ("Sachdeva star",           "star",          :lap, () -> star_join(complete_graph(100), 100)),
    ("grid 2D (uniform)",       "grid2_uniform", :lap, () -> grid2(256, 256)),
    ("grid 2D (anisotropic)",   "grid2_aniso",   :lap, () -> grid_aniso2(256; wy=1e-4)),
    ("grid 2D (high-contrast)", "grid2_hicon",   :lap, () -> grid_hicon2(256; rng=rng)),
    ("grid 3D (uniform)",       "grid3_uniform", :lap, () -> grid3(40)),
    ("grid 3D (anisotropic)",   "grid3_aniso",   :lap, () -> grid_aniso3(40; wy=1e-4, wz=1e-4)),
    ("grid 3D (high-contrast)", "grid3_hicon",   :lap, () -> grid_hicon3(40; rng=rng)),
    ("SPE10 (reservoir)",       "spe10",         :lap, :spe10),
]

manifest = IOBuffer(); println(manifest, "family,name,n,m,mode")
res = IOBuffer(); println(res, "family,name,n,m,mode,lamgplus_cycles,lamgplus_relres,lamgplus_ok")
opts = LAMGOptions(tol=tol, max_cycles=100)

for (fam, name, mode, build) in families
    if mode === :lap
        W = build === :spe10 ? read_mtx_sym(spe10) : build()
        W = (W + W') ./ 2; A = lap(W); n = size(A,1); m = div(nnz(A)-n, 2)
        rng2 = MersenneTwister(0xC0 + n); xt = randn(rng2, n); xt .-= mean(xt); b = A*xt
        setup(A; options=opts); solve(setup(A; options=opts), b; options=opts)   # warm-up
        (x, info) = solve(setup(A; options=opts), b; options=opts)
        rel = norm(A*x - b)/norm(b); cyc = info.cycles
    else  # :sdd  — grounded chimera, solved by LAMG+ via the grounded-Laplacian lift
        W = build(); W = (W + W') ./ 2; L = lap(W); n = size(L,1)
        rg = MersenneTwister(0xD0 + n); G = randperm(rg, n)[1:max(1, n÷100)]      # ground ~1%
        g = zeros(n); for i in G; g[i] = L[i,i]; end
        A = L + spdiagm(0 => g)                                                   # SDDM M
        m = div(nnz(A)-count(!iszero, diag(A)), 2)
        xt = randn(rg, n); b = A*xt
        I,J,V = findnz(A); I2=copy(I); J2=copy(J); V2=copy(V)                      # lift to (n+1) Laplacian
        for i in 1:n; g[i]!=0 && (push!(I2,i);push!(J2,n+1);push!(V2,-g[i]); push!(I2,n+1);push!(J2,i);push!(V2,-g[i])); end
        push!(I2,n+1); push!(J2,n+1); push!(V2,sum(g))
        Lt = sparse(I2,J2,V2,n+1,n+1); bt = vcat(b, -sum(b))
        setup(Lt; options=opts); solve(setup(Lt; options=opts), bt; options=opts) # warm-up
        (y, info) = solve(setup(Lt; options=opts), bt; options=opts)
        x = y[1:n] .- y[n+1]; rel = norm(A*x - b)/norm(b); cyc = info.cycles
    end
    ok = rel <= tol*10
    @printf("%-26s n=%-7d m=%-9d %-4s LAMG+  cyc=%-3d relres=%.2e %s\n",
            fam, size(A,1), m, mode, cyc, rel, ok ? "OK" : "FAIL")
    I,J,V = findnz(A)
    writedlm(joinpath(scratch, "$(name)_A.txt"), hcat(I,J,V), ',')
    writedlm(joinpath(scratch, "$(name)_b.txt"), b)
    println(manifest, "$fam,$name,$(size(A,1)),$m,$mode")
    println(res, "$fam,$name,$(size(A,1)),$m,$mode,$cyc,$rel,$(ok ? 1 : 0)")
end

write(joinpath(scratch, "manifest.csv"), String(take!(manifest)))
write(joinpath(scratch, "lamgplus.csv"), String(take!(res)))
println("\nWrote graphs + manifest.csv + lamgplus.csv to: ", scratch)
